name = "dictionary-web"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-19"

routes = [
    { pattern = "dict.erudify.org", zone_name = "erudify.org", custom_domain = true },
]

kv_namespaces = [
    { binding = "LLM_CACHE", id = "33dcdf22984a414bb530a611e3032e20", preview_id = "33dcdf22984a414bb530a611e3032e20" },
]

[assets]
directory = "assets"

[build]
command = """
mkdir -p assets/pkg &&
cp public/* assets/ &&
npx tailwindcss --minify -i style/tailwind.css -o assets/style.css &&
wasm-pack build --out-dir assets/pkg --no-typescript --release --target web --out-name client --features hydrate --no-default-features &&
worker-build --release --features ssr --no-default-features
"""
