name = "dictionary-web"
main = "build/worker/shim.mjs"
compatibility_date = "2024-07-13"

routes = [
    { pattern = "dict.erudify.org", zone_name = "erudify.org", custom_domain = true },
]

kv_namespaces = [
    { binding = "LLM_CACHE", id = "33dcdf22984a414bb530a611e3032e20", preview_id = "33dcdf22984a414bb530a611e3032e20" },
]

[build]
command = """
mkdir -p pkg &&
cp public/* pkg/ &&
npx tailwindcss --minify -i style/tailwind.css -o pkg/style.css &&
wasm-pack build --no-typescript --release --target web --out-name client --features hydrate --no-default-features &&
worker-build --release --features ssr --no-default-features
"""

[env.quick]
kv_namespaces = [
    { binding = "LLM_CACHE", id = "33dcdf22984a414bb530a611e3032e20", preview_id = "33dcdf22984a414bb530a611e3032e20" },
]
[env.quick.build]
command = """
mkdir -p pkg &&
cp public/* pkg/ &&
npx tailwindcss --minify -i style/tailwind.css -o pkg/style.css &&
wasm-pack build --no-typescript --no-opt --target web --out-name client --features hydrate --no-default-features &&
worker-build --no-opt --features ssr --no-default-features
"""
